--Display names by descendeing order
SELECT ENAME FROM EMP ORDER BY ENAME DESC

--Display all employes,commission,salary from department 10
SELECT ENAME,SAL,COMM FROM EMP WHERE DEPTNO=10

--all employees in department 10 and 20
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20

SELECT * FROM EMP WHERE DEPTNO in (10,20)

--Show all managers
SELECT * FROM EMP WHERE JOB='MANAGER'

--Show employees whose salary between 2k and 5k dollars
SELECT * FROM EMP WHERE SAL BETWEEN 2000 and 5000

--Show Employees whose commision is null
SELECT * FROM EMP WHERE COMM IS NULL

--cALCULATE ANNUAL CTC
SELECT COMM, ISNULL(COMM,0)FROM EMP
SELECT ENAME,SAL,COMM,12*(SAL+ISNULL(COMM,0))AS CTC FROM EMP

--DISPLAY MIN, MAX, AVG, SUM OF SALARIES OF EMPLOYEES
SELECT AVG(SAL) AS 'AVG', MAX(SAL) AS 'MAX',SUM(SAL) AS 'SUM' FROM EMP

SELECT GETDATE AS 'TODAY' PRINT GETDATE()

SELECT DATEDIFF(YEAR, '2017/08/25', GETDATE()) AS DATEDIFF

SELECT	ENAME,HIREDATE,DATEDIFF(YEAR,HIREDATE,GETDATE())
AS 'TENURE' FROM EMP

SELECT * FROM EMP WHERE ENAME LIKE 'A%';

SELECT DISTINCT DEPTNO FROM EMP

SELECT TOP 3 * FROM EMP ORDER BY SAL DESC

SELECT DEPTNO,COUNT(DEPTNO) FROM EMP GROUP BY DEPTNO

SELECT JOB,COUNT(JOB) FROM EMP GROUP BY JOB

SELECT DEPTNO,JOB,COUNT(*) AS EMPLOYEECOUNT FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO

SELECT * FROM EMP