// <auto-generated />
namespace SimpleEFApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2_customer_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_customer_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202305181120404_v2_customer_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
