SELECT * FROM EMP

--ALL EMPLOYEES IN THE SAME DEPARTMENT OF SMITH
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME='SMITH')

--ALL EMPLOYEES WITH THE SAME SALARY OF SCOTT
SELECT * FROM EMP WHERE SAL IN (SELECT SAL FROM EMP WHERE ENAME='SCOTT')

--ALL EMPLOYEES WITH THE SAME POST AS BLAKE
	SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME='BLAKE')

--join DEPTNAME and EMPNAME create a table,
SELECT DEPT.DNAME,EMP.ENAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMP.ENAME

--display all dmanes and employee names
SELECT DEPT.DNAME,EMP.ENAME
FROM EMP RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMP.ENAME

--display dept where there are no employees
SELECT DEPT.DNAME,EMP.ENAME
FROM EMP RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.ENAME IS NULL
ORDER BY DEPT.DNAME

--display all emp and their manager name
SELECT X.ENAME,Y.ENAME AS BOSS FROM
EMP X LEFT JOIN EMP Y
ON X.MGR = Y.EMPNO
ORDER BY X.ENAME

--display all empname, departmentName and their manager name
SELECT X.ENAME,DEPT.DNAME,Y.ENAME AS 'BOSS' FROM
EMP X JOIN DEPT
ON X.DEPTNO=DEPT.DEPTNO
LEFT JOIN EMP Y
ON X.MGR=Y.EMPNO
